moved to new archiso version that broke backward compatibility

diff --git a/mkarchiso b/mkarchiso
--- a/mkarchiso
+++ b/mkarchiso
@@ -11,11 +11,12 @@ run_cmd=""
 quiet="y"
 pacman_conf="/etc/pacman.conf"
 export iso_label="ASGARD_$(date +%Y%m)"
-iso_publisher="plugnburn <http://gist.github.com/plugnburn>"
+iso_publisher="plugnburn <http://github.com/plugnburn>"
 iso_application="Asgard"
 install_dir="arch"
 work_dir="work"
 out_dir="out"
+sfs_comp="xz"
 
 # Show an INFO message
 # $1: message string
@@ -38,75 +39,29 @@ _msg_error() {
     fi
 }
 
-# Show space usage similar to df, but better formatted.
-# $1: mount-point or mounted device.
-_show_space_usage () {
-    local _where="${1}"
-    local _fs _total _used _avail _pct_u=0 _mnt
-    read _fs _total _used _avail _pct_u _mnt < <(df -m "${_where}" | tail -1) &> /dev/null
-    _msg_info "Total: ${_total} MiB (100%) | Used: ${_used} MiB (${_pct_u}) | Avail: ${_avail} MiB ($((100 - ${_pct_u%\%}))%)"
-}
-
 _chroot_init() {
-    if [[ -f "${work_dir}/mkarchiso.init" ]]; then
-        _msg_info "Initial enviroment already installed, skipping."
-    else
-        mkdir -p ${work_dir}/root-image
-        _pacman "syslinux"
-        : > "${work_dir}/mkarchiso.init"
-    fi
+    mkdir -p ${work_dir}/airootfs
+    _pacman "syslinux"
 }
 
 _chroot_run() {
-    eval arch-chroot ${work_dir}/root-image "${run_cmd}"
+    eval arch-chroot ${work_dir}/airootfs "${run_cmd}"
 }
 
-# Mount a filesystem (trap signals in case of error for unmounting it
-# $1: source image
-# $2: mount-point
-_mount_fs() {
-    local _src="${1}"
-    local _dst="${2}"
-    trap "_umount_fs ${_src}" EXIT HUP INT TERM
-    mkdir -p "${_dst}"
-    _msg_info "Mounting '${_src}' on '${_dst}'"
-    mount "${_src}" "${_dst}"
-    _show_space_usage "${_dst}"
+_mount_airootfs() {
+    trap "_umount_airootfs" EXIT HUP INT TERM
+    mkdir -p "${work_dir}/mnt/airootfs"
+    _msg_info "Mounting '${work_dir}/airootfs.img' on '${work_dir}/mnt/airootfs'"
+    mount "${work_dir}/airootfs.img" "${work_dir}/mnt/airootfs"
+    _msg_info "Done!"
 }
 
-# Unmount a filesystem (and untrap signals)
-# $1: mount-point or device/image
-_umount_fs() {
-    local _dst="${1}"
-    _show_space_usage "${_dst}"
-    _msg_info "Unmounting '${_dst}'"
-    umount "${_dst}"
-    rmdir "${_dst}"
+_umount_airootfs() {
+    _msg_info "Unmounting '${work_dir}/mnt/airootfs'"
+    umount "${work_dir}/mnt/airootfs"
+    _msg_info "Done!"
+    rmdir "${work_dir}/mnt/airootfs"
     trap - EXIT HUP INT TERM
-}
-
-# Compare if a file/directory (source) is newer than other file (target)
-# $1: source file/directory
-# $2: target file
-# return: 0 if target does not exists or if target is older than source.
-#         1 if target is newer than source
-_is_directory_changed() {
-    local _src="${1}"
-    local _dst="${2}"
-
-    if [ -e "${_dst}" ]; then
-        if [[ $(find ${_src} -newer ${_dst} | wc -l) -gt 0 ]]; then
-            _msg_info "Target '${_dst}' is older than '${_src}', updating."
-            rm -f "${_dst}"
-            return 0
-        else
-            _msg_info "Target '${_dst}' is up to date with '${_src}', skipping."
-            return 1
-        fi
-    else
-        _msg_info "Target '${_dst}' does not exist, making it from '${_src}'"
-        return 0
-    fi
 }
 
 # Show help usage, with an exit status.
@@ -116,7 +71,7 @@ _usage ()
     echo "usage ${app_name} [options] command <command options>"
     echo " general options:"
     echo "    -p PACKAGE(S)    Package(s) to install, can be used multiple times"
-    echo "    -r <command>     Run <command> inside root-image"
+    echo "    -r <command>     Run <command> inside airootfs"
     echo "    -C <file>        Config file for pacman."
     echo "                     Default: '${pacman_conf}'"
     echo "    -L <label>       Set a label for the disk"
@@ -132,6 +87,8 @@ _usage ()
     echo "                     Default: '${work_dir}'"
     echo "    -o <out_dir>     Set the output directory"
     echo "                     Default: '${out_dir}'"
+    echo "    -c <comp_type>   Set SquashFS compression type (gzip, lzma, lzo, xz)"
+    echo "                     Default: '${sfs_comp}'"
     echo "    -v               Enable verbose output"
     echo "    -h               This message"
     echo " commands:"
@@ -143,17 +100,15 @@ _usage ()
     echo "      run command specified by -r"
     echo "   prepare"
     echo "      build all images"
-    echo "   checksum"
-    echo "      make a checksum.md5 for self-test"
     echo "   pkglist"
-    echo "      make a pkglist.txt of packages installed on root-image"
+    echo "      make a pkglist.txt of packages installed on airootfs"
     echo "   iso <image name>"
     echo "      build an iso image from the working dir"
     exit ${1}
 }
 
 # Shows configuration according to command mode.
-# $1: init | install | run | prepare | checksum | iso
+# $1: init | install | run | prepare | iso
 _show_config () {
     local _mode="$1"
     echo
@@ -175,8 +130,6 @@ _show_config () {
             ;;
         prepare)
             ;;
-        checksum)
-            ;;
         pkglist)
             ;;
         iso)
@@ -189,186 +142,104 @@ _show_config () {
     echo
 }
 
-# Install desired packages to root-image
+# Install desired packages to airootfs
 _pacman ()
 {
-    _msg_info "Installing packages to '${work_dir}/root-image/'..."
+    _msg_info "Installing packages to '${work_dir}/airootfs/'..."
 
     if [[ "${quiet}" = "y" ]]; then
-        pacstrap -C "${pacman_conf}" -c -d -G -M "${work_dir}/root-image" $* &> /dev/null
+        pacstrap -C "${pacman_conf}" -c -d -G -M "${work_dir}/airootfs" $* &> /dev/null
     else
-        pacstrap -C "${pacman_conf}" -c -d -G -M "${work_dir}/root-image" $*
+        pacstrap -C "${pacman_conf}" -c -d -G -M "${work_dir}/airootfs" $*
     fi
 
     _msg_info "Packages installed successfully!"
 }
 
-# Cleanup root-image
+# Cleanup airootfs
 _cleanup () {
-    _msg_info "Cleaning up what we can on root-image..."
+    _msg_info "Cleaning up what we can on airootfs..."
 
     # Delete initcpio image(s)
-    if [[ -d "${work_dir}/root-image/boot" ]]; then
-        find "${work_dir}/root-image/boot" -type f -name '*.img' -delete
+    if [[ -d "${work_dir}/airootfs/boot" ]]; then
+        find "${work_dir}/airootfs/boot" -type f -name '*.img' -delete
     fi
     # Delete kernel(s)
-    if [[ -d "${work_dir}/root-image/boot" ]]; then
-        find "${work_dir}/root-image/boot" -type f -name 'vmlinuz*' -delete
+    if [[ -d "${work_dir}/airootfs/boot" ]]; then
+        find "${work_dir}/airootfs/boot" -type f -name 'vmlinuz*' -delete
     fi
     # Delete pacman database sync cache files (*.tar.gz)
-    if [[ -d "${work_dir}/root-image/var/lib/pacman" ]]; then
-        find "${work_dir}/root-image/var/lib/pacman" -maxdepth 1 -type f -delete
+    if [[ -d "${work_dir}/airootfs/var/lib/pacman" ]]; then
+        find "${work_dir}/airootfs/var/lib/pacman" -maxdepth 1 -type f -delete
     fi
     # Delete pacman database sync cache
-    if [[ -d "${work_dir}/root-image/var/lib/pacman/sync" ]]; then
-        find "${work_dir}/root-image/var/lib/pacman/sync" -delete
+    if [[ -d "${work_dir}/airootfs/var/lib/pacman/sync" ]]; then
+        find "${work_dir}/airootfs/var/lib/pacman/sync" -delete
     fi
     # Delete pacman package cache
-    if [[ -d "${work_dir}/root-image/var/cache/pacman/pkg" ]]; then
-        find "${work_dir}/root-image/var/cache/pacman/pkg" -type f -delete
+    if [[ -d "${work_dir}/airootfs/var/cache/pacman/pkg" ]]; then
+        find "${work_dir}/airootfs/var/cache/pacman/pkg" -type f -delete
     fi
     # Delete all log files, keeps empty dirs.
-    if [[ -d "${work_dir}/root-image/var/log" ]]; then
-        find "${work_dir}/root-image/var/log" -type f -delete
+    if [[ -d "${work_dir}/airootfs/var/log" ]]; then
+        find "${work_dir}/airootfs/var/log" -type f -delete
     fi
     # Delete all temporary files and dirs
-    if [[ -d "${work_dir}/root-image/var/tmp" ]]; then
-        find "${work_dir}/root-image/var/tmp" -mindepth 1 -delete
+    if [[ -d "${work_dir}/airootfs/var/tmp" ]]; then
+        find "${work_dir}/airootfs/var/tmp" -mindepth 1 -delete
     fi
     # Delete package pacman related files.
     find "${work_dir}" \( -name "*.pacnew" -o -name "*.pacsave" -o -name "*.pacorig" \) -delete
     _msg_info "Done!"
 }
 
-# Makes a SquashFS filesystem image of file/directory passes as argument with desired compression.
-# $1: Source file/directory
-# $2: SquashFS compression type (gzip | lzo | xz)
-_mksfs () {
-    local _src="${1}"
-    local _sfs_comp="${2}"
-
-    if [[ ! -e "${work_dir}/${_src}" ]]; then
-        _msg_error "The path '${work_dir}/${_src}' does not exist" 1
-    fi
-
-    local _sfs_img="${work_dir}/${_src}.sfs"
-
-    _msg_info "Creating SquashFS image for '${work_dir}/${_src}', This may take some time..."
-    local _seconds=${SECONDS}
-    if [[ "${quiet}" = "y" ]]; then
-        mksquashfs "${work_dir}/${_src}" "${_sfs_img}" -noappend -comp "${_sfs_comp}" -no-progress &> /dev/null
-    else
-        mksquashfs "${work_dir}/${_src}" "${_sfs_img}" -noappend -comp "${_sfs_comp}" -no-progress
-    fi
-    _seconds=$((SECONDS - _seconds))
-    printf "[mkarchiso] INFO: Image creation done in %02d:%02d minutes\n" $((_seconds / 60)) $((_seconds % 60))
-}
-
 # Makes a filesystem from a source directory.
-# $1: Source directory
-# $2: Target filesystem type (ext4 | ext3 | ext2 | xfs | btrfs)
-# $3: Size of target filesystem. Can be an absolute value in MiB, or relative value of desired free space (1% - 99%)
-_mkfs () {
-    local _src="${1}"
-    local _fs_type="${2}"
-    local _fs_size="${3}"
-
-    local _fs_src="${work_dir}/${_src}"
-    local _fs_img="${work_dir}/${_src}.fs"
-
-    if [[ ! -e "${_fs_src}" ]]; then
-        _msg_error "The path '${_fs_src}' does not exist" 1
+_mkairootfs () {
+    if [[ ! -e "${work_dir}/airootfs" ]]; then
+        _msg_error "The path '${work_dir}/airootfs' does not exist" 1
     fi
 
-    local _spc_used
-    _spc_used=$(du -sxm "${_fs_src}" | awk '{print $1}')
-
-    # Caculate FS size with desired % of free space, adds 10% overhead to used space.
-    if [[ ${_fs_size} != ${_fs_size%\%} ]]; then
-        if [[ ${_fs_size%\%} -le 0 || ${_fs_size%\%} -ge 100 ]]; then
-            _msg_error "Invalid percentage of free space specified '${_fs_size}' on '${_src}', should be 0% < x < 100%" 1
-        fi
-        _fs_size=$((_spc_used * 110 / (100 - ${_fs_size%\%})))
-    else
-        local _spc_used_over=$((_spc_used * 11 / 10))
-        if [[ ${_fs_size} -lt ${_spc_used_over} ]]; then
-            _msg_error "Filesystem size specified '${_fs_size}' MiB for '${_src}' is too small, must be at least '${_spc_used_over}' MiB" 1
-        fi
-    fi
-
-    #fix for buggy 32-bit e2fsprogs versions
-    [[ ${_fs_size} > 2047 ]] &&  _fs_size=2047;
-
-    _msg_info "Creating ${_fs_type} image of ${_fs_size} MiB..."
-    rm -f "${_fs_img}"
-    truncate -s ${_fs_size}M "${_fs_img}"
+    _msg_info "Creating ext4 image of 32GiB..."
+    truncate -s 32G "${work_dir}/airootfs.img"
     local _qflag=""
     if [[ ${quiet} == "y" ]]; then
         _qflag="-q"
     fi
-    case "${_fs_type}" in
-        ext4)
-            mkfs.ext4 ${_qflag} -O ^has_journal -E lazy_itable_init=0 -m 0 -F "${_fs_img}"
-            tune2fs -c 0 -i 0 "${_fs_img}" &> /dev/null
-            ;;
-        ext3)
-            mkfs.ext3 ${_qflag} -m 0 -F "${_fs_img}"
-            tune2fs -c 0 -i 0 "${_fs_img}" &> /dev/null
-            ;;
-        ext2)
-            mkfs.ext2 ${_qflag} -m 0 -F "${_fs_img}"
-            tune2fs -c 0 -i 0 "${_fs_img}" &> /dev/null
-            ;;
-        xfs)
-            mkfs.xfs ${_qflag} "${_fs_img}"
-            ;;
-        btrfs)
-            mkfs.btrfs -M "${_fs_img}"
-            ;;
-        *)
-            _msg_error "Invalid filesystem: ${_fs_type}" 1
-            ;;
-    esac
+    mkfs.ext4 ${_qflag} -O ^has_journal -E lazy_itable_init=0 -m 0 -F "${work_dir}/airootfs.img"
+    tune2fs -c 0 -i 0 "${work_dir}/airootfs.img" &> /dev/null
     _msg_info "Done!"
-    _mount_fs "${_fs_img}" "${work_dir}/mnt/${_src}"
-    _msg_info "Copying '${_fs_src}/' to '${work_dir}/mnt/${_src}/'..."
-    cp -aT "${_fs_src}/" "${work_dir}/mnt/${_src}/"
+    _mount_airootfs
+    _msg_info "Copying '${work_dir}/airootfs/' to '${work_dir}/mnt/airootfs/'..."
+    cp -aT "${work_dir}/airootfs/" "${work_dir}/mnt/airootfs/"
     _msg_info "Done!"
-    _umount_fs "${work_dir}/mnt/${_src}"
+    _umount_airootfs
+    mkdir -p "${work_dir}/iso/${install_dir}/${arch}"
+    _msg_info "Creating SquashFS image, this may take some time..."
+    if [[ "${quiet}" = "y" ]]; then
+        mksquashfs "${work_dir}/airootfs.img" "${work_dir}/iso/${install_dir}/${arch}/airootfs.sfs" -noappend -comp "${sfs_comp}" -no-progress &> /dev/null
+    else
+        mksquashfs "${work_dir}/airootfs.img" "${work_dir}/iso/${install_dir}/${arch}/airootfs.sfs" -noappend -comp "${sfs_comp}" -no-progress
+    fi
+    _msg_info "Done!"
+    rm ${work_dir}/airootfs.img
 }
 
-command_checksum () {
-    _show_config checksum
-
-    local _chk_arch
-
-    for _chk_arch in i686 x86_64; do
-        if _is_directory_changed "${work_dir}/iso/${install_dir}" "${work_dir}/iso/${install_dir}/checksum.${_chk_arch}.md5"; then
-            _msg_info "Creating checksum file for self-test (${_chk_arch})..."
-            cd "${work_dir}/iso/${install_dir}"
-            if [[ -d "${_chk_arch}" ]]; then
-                md5sum aitab > checksum.${_chk_arch}.md5
-                find ${_chk_arch} -type f -print0 | xargs -0 md5sum >> checksum.${_chk_arch}.md5
-                if [[ -d "any" ]]; then
-                    find any -type f -print0 | xargs -0 md5sum >> checksum.${_chk_arch}.md5
-                fi
-            fi
-            cd ${OLDPWD}
-            _msg_info "Done!"
-        fi
-    done
+_mkchecksum () {
+    _msg_info "Creating checksum file for self-test..."
+    cd "${work_dir}/iso/${install_dir}/${arch}"
+    md5sum airootfs.sfs > airootfs.md5
+    cd ${OLDPWD}
+    _msg_info "Done!"
 }
 
 command_pkglist () {
     _show_config pkglist
 
-    if _is_directory_changed "${work_dir}/root-image/var/lib/pacman/local" "${work_dir}/iso/${install_dir}/pkglist.${arch}.txt"; then
-        _msg_info "Creating a list of installed packages on live-enviroment..."
-        pacman -Sl -r "${work_dir}/root-image" --config "${pacman_conf}" | \
-            awk '/\[installed\]$/ {print $1 "/" $2 "-" $3}' > \
-            "${work_dir}/iso/${install_dir}/pkglist.${arch}.txt"
-        _msg_info "Done!"
-    fi
+    _msg_info "Creating a list of installed packages on live-enviroment..."
+    pacman -Sl -r "${work_dir}/airootfs" --config "${pacman_conf}" | \
+        awk '/\[installed\]$/ {print $1 "/" $2 "-" $3}' > \
+        "${work_dir}/iso/${install_dir}/pkglist.${arch}.txt"
+    _msg_info "Done!"
 
 }
 
@@ -393,67 +264,39 @@ command_iso () {
 
     _show_config iso
 
-    if _is_directory_changed "${work_dir}/iso" "${out_dir}/${img_name}"; then
-        mkdir -p ${out_dir}
-        _msg_info "Creating ISO image..."
-        local _qflag=""
-        if [[ ${quiet} == "y" ]]; then
-            _qflag="-quiet"
-        fi
-        xorriso -as mkisofs ${_qflag} \
-            -iso-level 3 \
-            -full-iso9660-filenames \
-            -volid "${iso_label}" \
-            -appid "${iso_application}" \
-            -publisher "${iso_publisher}" \
-            -preparer "prepared by mkarchiso" \
-            -eltorito-boot isolinux/isolinux.bin \
-            -eltorito-catalog isolinux/boot.cat \
-            -no-emul-boot -boot-load-size 4 -boot-info-table \
-            -isohybrid-mbr ${work_dir}/iso/isolinux/isohdpfx.bin \
-            ${_iso_efi_boot_args} \
-            -output "${out_dir}/${img_name}" \
-            "${work_dir}/iso/"
-        _msg_info "Done! | $(ls -sh ${out_dir}/${img_name})"
+    mkdir -p ${out_dir}
+    _msg_info "Creating ISO image..."
+    local _qflag=""
+    if [[ ${quiet} == "y" ]]; then
+        _qflag="-quiet"
     fi
+    xorriso -as mkisofs ${_qflag} \
+        -iso-level 3 \
+        -full-iso9660-filenames \
+        -volid "${iso_label}" \
+        -appid "${iso_application}" \
+        -publisher "${iso_publisher}" \
+        -preparer "prepared by mkarchiso" \
+        -eltorito-boot isolinux/isolinux.bin \
+        -eltorito-catalog isolinux/boot.cat \
+        -no-emul-boot -boot-load-size 4 -boot-info-table \
+        -isohybrid-mbr ${work_dir}/iso/isolinux/isohdpfx.bin \
+        ${_iso_efi_boot_args} \
+        -output "${out_dir}/${img_name}" \
+        "${work_dir}/iso/"
+    _msg_info "Done! | $(ls -sh ${out_dir}/${img_name})"
 }
 
-# Parse aitab and create each filesystem specified on that, and push it in "iso" directory.
+# create airootfs.sfs filesystem, and push it in "iso" directory.
 command_prepare () {
-    if [[ ! -f "${work_dir}/iso/${install_dir}/aitab" ]]; then
-         _msg_error "The file '${work_dir}/iso/${install_dir}/aitab' does not exist." 1
-    fi
     _show_config prepare
 
     _cleanup
-    local _aitab_img _aitab_mnt _aitab_arch _aitab_sfs_comp _aitab_fs_type _aitab_fs_size
-    while read _aitab_img _aitab_mnt _aitab_arch _aitab_sfs_comp _aitab_fs_type _aitab_fs_size ; do
-        if [[ ${_aitab_img} =~ ^# ]]; then
-            continue
-        fi
-        if [[ "${_aitab_arch}" != "any" && "${_aitab_arch}" != "${arch}" ]]; then
-            continue
-        fi
-        local _src="${work_dir}/${_aitab_img}"
-        local _dst="${work_dir}/iso/${install_dir}/${_aitab_arch}"
-        mkdir -p "${_dst}"
-        if [[ ${_aitab_fs_type} != "none" ]]; then
-            if _is_directory_changed "${_src}" "${_dst}/${_aitab_img}.fs.sfs"; then
-                _mkfs ${_aitab_img} ${_aitab_fs_type} ${_aitab_fs_size}
-                _mksfs ${_aitab_img}.fs ${_aitab_sfs_comp}
-                mv "${_src}.fs.sfs" "${_dst}"
-                rm "${_src}.fs"
-            fi
-        else
-            if _is_directory_changed "${_src}" "${_dst}/${_aitab_img}.sfs"; then
-                _mksfs ${_aitab_img} ${_aitab_sfs_comp}
-                mv "${work_dir}/${_aitab_img}.sfs" "${_dst}"
-            fi
-        fi
-    done < "${work_dir}/iso/${install_dir}/aitab"
+    _mkairootfs
+    _mkchecksum
 }
 
-# Install packages on root-image.
+# Install packages on airootfs.
 # A basic check to avoid double execution/reinstallation is done via hashing package names.
 command_install () {
     if [[ ! -f "${pacman_conf}" ]]; then
@@ -470,14 +313,7 @@ command_install () {
 
     _show_config install
 
-    local _pkg_list_hash
-    _pkg_list_hash=$(echo ${pkg_list} | sort -u | md5sum | cut -c1-32)
-    if [[ -f "${work_dir}/install.${_pkg_list_hash}" ]]; then
-        _msg_info "These packages are already installed, skipping."
-    else
-        _pacman "${pkg_list}"
-        : > "${work_dir}/install.${_pkg_list_hash}"
-    fi
+    _pacman "${pkg_list}"
 }
 
 command_init() {
@@ -494,7 +330,7 @@ if [[ ${EUID} -ne 0 ]]; then
     _msg_error "This script must be run as root." 1
 fi
 
-while getopts 'p:r:C:L:P:A:D:w:o:vh' arg; do
+while getopts 'p:r:C:L:P:A:D:w:o:c:vh' arg; do
     case "${arg}" in
         p) pkg_list="${pkg_list} ${OPTARG}" ;;
         r) run_cmd="${OPTARG}" ;;
@@ -505,6 +341,7 @@ while getopts 'p:r:C:L:P:A:D:w:o:vh' arg; do
         D) install_dir="${OPTARG}" ;;
         w) work_dir="${OPTARG}" ;;
         o) out_dir="${OPTARG}" ;;
+        c) sfs_comp="${OPTARG}" ;;
         v) quiet="n" ;;
         h|?) _usage 0 ;;
         *)
@@ -534,9 +371,6 @@ case "${command_name}" in
         ;;
     prepare)
         command_prepare
-        ;;
-    checksum)
-        command_checksum
         ;;
     pkglist)
         command_pkglist
